# Javascript Node CircleCI 2.0 configuration file
#
# Check {{ '/2.0/language-javascript/' | docs_url }} for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: 'cimg/node:14.14.0'

jobs:
  publish:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Publish app
          command: ./node_modules/vsce/out/vsce publish -p $VSCODE_MARKETPLACE_TOKEN

workflows:
  version: 2
  publish:
    jobs:
      - publish
